In [1]:
# Hello, World! of PRyMordial
import PRyM.PRyM_main as PRyMmain
%time myPRyM = PRyMmain.PRyMclass()

CPU times: user 19.1 s, sys: 171 ms, total: 19.3 s
Wall time: 19.5 s


In [2]:
# [Neff , Ω_ν h^2 × 10^6 (rel), ∑ m_ν / (Ω_ν h^2) [eV], YP (CMB), YP (BBN), D/H × 10^5, 3He/H × 10^5, 7Li/H × 10^10]
myPRyM.PRyMresults()

array([ 3.04438852,  5.69940717, 93.03360798,  0.24555799,  0.24688388,
        2.45571913,  1.04109377,  5.4396027 ])

In [3]:
# Individual call for each observable
myPRyM.Neff(),myPRyM.Omeganurel(),myPRyM.Omeganunonrel(),myPRyM.YPCMB(),myPRyM.YPBBN(),myPRyM.DoH(),myPRyM.He3oH(),myPRyM.Li7oH(),

(3.0443885202770353,
 5.699407167709695,
 0.010748803811036312,
 0.24555799256654465,
 0.24688388433548078,
 2.4557191299983862e-05,
 1.0410937694846855e-05,
 5.439602704563259e-10)

In [4]:
# Change of input parameter
import PRyM.PRyM_init as PRyMini
PRyMini.tau_n = 879 # s
myPRyMnewtau = PRyMmain.PRyMclass()

In [5]:
# Results with new neutron lifetime
myPRyMnewtau.PRyMresults()

array([ 3.04438852,  5.69940717, 93.03360798,  0.24568768,  0.24701405,
        2.45568435,  1.04128876,  5.44031987])

In [6]:
# Change of nuclear rates
PRyMini.nacreii_flag = True
PRyMini.ReloadKeyRates()
myPRyMnacreii = PRyMmain.PRyMclass()

In [7]:
# Results with NACRE-II key nuclear rates
myPRyMnacreii.PRyMresults()

array([ 3.04438852,  5.69940717, 93.03360798,  0.24560241,  0.24692846,
        2.53091765,  1.04596038,  5.26793753])

In [8]:
# Use small nuclear network comprising key rates for YP and D/H
PRyMini.smallnet_flag = True
%time PRyMmain.PRyMclass().PRyMresults()

CPU times: user 10.8 s, sys: 35.9 ms, total: 10.8 s
Wall time: 10.8 s


array([ 3.04438852,  5.69940717, 93.03360798,  0.24559377,  0.24691979,
        2.52938906,  1.04631994,  5.32182768])

In [10]:
############################################
# Code to reproduce Figure 2 of 2307.07061 #
############################################
# Restore neutron lifetime of PDG 2023
PRyMini.tau_n = 878.4 # s
# Include incomplete decoupling in a(T)
aTid_flag = True
# Recompute the background from scratch
PRyMini.compute_bckg_flag = True
# Save the background in PRyMrates/thermo
PRyMini.save_bckg_flag = True
# Recompute n <--> p rates from scratch
PRyMini.compute_nTOp_flag = True
# Save n <--> p rates in PRyMrates/nTOp
PRyMini.save_nTOp_flag = True
# Include only key rates in nuclear network
PRyMini.smallnet_flag = True
# NACRE II compilation for key rates
PRyMini.nacreii_flag = True
# compute PRyM observables
YP,DoHx1e5,He3oHx1e5,Li7oHx1e10 = PRyMmain.PRyMclass().PRyMresults()[4:8]

In [11]:
# Change in etab does not require to recompute background and p <--> n
PRyMini.compute_bckg_flag = False
PRyMini.save_bckg_flag = False
PRyMini.compute_nTOp_flag = False
PRyMini.save_nTOp_flag = False
# Compute PRyMordial obs will now be faster!
%time YP,DoHx1e5,He3oHx1e5,Li7oHx1e10 = PRyMmain.PRyMclass().PRyMresults()[4:8]

CPU times: user 3.18 s, sys: 18 ms, total: 3.2 s
Wall time: 3.22 s


In [12]:
# PDG plot
npoints = 20
import numpy as np
etabvec = np.logspace(-10,-9,npoints)
# Initialization of array of observables
YP_vec, DoH_vec, He3oH_vec, Li7oH_vec = np.zeros((4,npoints))
for i in range(npoints):
    # Update value of baryon-to-photon ratio
    PRyMini.eta0b = etabvec[i]
    # Store obs computed for the new eta
    YP_vec[i], DoH_vec[i], He3oH_vec[i], Li7oH_vec[i] = PRyMmain.PRyMclass().PRyMresults()[4:8]

In [15]:
# Sample of array values for Figure 2 in 2307.07061
# Figure 2 obtained w/ 50 points + PDG 2023 inputs + large nuclear network
print("etab10 : ",etabvec*1e+10)
print("YP : ",YP_vec)
print("DoH : ",DoH_vec)

etab10 :  [ 1.          1.12883789  1.27427499  1.43844989  1.62377674  1.83298071
  2.06913808  2.33572147  2.6366509   2.97635144  3.35981829  3.79269019
  4.2813324   4.83293024  5.45559478  6.15848211  6.95192796  7.8475997
  8.8586679  10.        ]
YP :  [0.22161251 0.22437462 0.22684817 0.22907052 0.2310983  0.23296737
 0.23470055 0.23632004 0.2378371  0.23928363 0.24065009 0.24197766
 0.24325356 0.24450142 0.2457055  0.2468765  0.24803865 0.24917416
 0.25029507 0.25139384]
DoH :  [46.30052103 38.02213446 31.10599782 25.48678168 20.88056167 17.11499746
 14.05804238 11.57658758  9.55382206  7.88410631  6.51617202  5.39040614
  4.45066057  3.67684098  3.03694638  2.4915611   2.03768081  1.65410559
  1.33299631  1.06101458]


In [28]:
############################################
# Code to reproduce Figure 3 of 2307.07061 #
############################################
# SM MC run
num_it = 80 # toy MC ... 10K used for Figure 3 w/ large network
import numpy as np
YP_vec, DoH_vec, He3oH_vec, Li7oH_vec = np.zeros((4,num_it))
# Baryon eta from Planck 18 (no BBN prior)
mean_eta0b = PRyMini.Omegabh2_to_eta0b*0.02230
std_eta0b = PRyMini.Omegabh2_to_eta0b*2*1.e-4
# Neutron lifetime from PDG 2023
mean_tau_n = 878.4 # s
std_tau_n = 0.5 # s

In [29]:
# Compute primordial abundances at each iteration
def ComputeAbundances(i):
    # Settings to speed up the SM MC
    PRyMini.recompute_bckg = False
    PRyMini.recompute_nTOp_rates = False
    # Small network used: Set to False for a more reliable prediction of Li7
    PRyMini.smallnet_flag = True
    PRyMini.num_reactions = 12 # for the large network, set this to be 63
    # Gaussian prior on baryon-to-photon ratio
    PRyMini.eta0b = np.random.normal(mean_eta0b,std_eta0b)
    # Gaussian prior on neutron lifetime
    PRyMini.tau_n = np.random.normal(mean_tau_n,std_tau_n)
    # Log-normal prior on nuclear rates
    # For the large network, many more ... see PRyM_init.py
    PRyMini.p_npdg,PRyMini.p_dpHe3g,PRyMini.p_ddHe3n,PRyMini.p_ddtp,PRyMini.p_tpag,PRyMini.p_tdan,PRyMini.p_taLi7g,PRyMini.p_He3ntp,PRyMini.p_He3dap,PRyMini.p_He3aBe7g,PRyMini.p_Be7nLi7p,PRyMini.p_Li7paa = np.random.normal(0,1,PRyMini.num_reactions)
    # Adopt NACRE II compilation for key rates
    PRyMini.nacreii_flag = True
    PRyMini.ReloadKeyRates()
    return PRyMmain.PRyMclass().PRyMresults()[4:8]

In [30]:
# Parallelizing w/ joblib + multiprocessing
from joblib import Parallel, delayed
import multiprocessing
num_cpu = int(multiprocessing.cpu_count())
FinalAbundances = Parallel(n_jobs = num_cpu)(delayed(ComputeAbundances)((i)) 
for i in range(num_it))
YP_vec, DoH_vec, He3oH_vec, Li7oH_vec = np.array(FinalAbundances).transpose()

In [31]:
# Statistics for primordial helium-4 mass fraction
print("Mean", np.mean(YP_vec), " +-", np.std(YP_vec))
np.quantile(YP_vec,[0.16,0.5,0.84])

Mean 0.2468051799540944  +- 0.00014796011976920647


array([0.24665914, 0.24680892, 0.24696653])

In [32]:
# Statistics for primordial deuterium relative H number density
print("Mean", np.mean(DoH_vec), " +-", np.std(DoH_vec))
np.quantile(DoH_vec,[0.16,0.5,0.84])

Mean 2.523145773036314  +- 0.10212326637028163


array([2.42822918, 2.51904284, 2.61839101])