In [1]:
# Vary Neff
import PRyM.PRyM_init as PRyMini
import PRyM.PRyM_main as PRyMmain
PRyMini.aTid_flag = True
PRyMini.compute_bckg_flag = True
PRyMini.compute_nTOp_flag = True
PRyMini.DeltaNeff = 0.
PRyMSM = PRyMmain.PRyMclass()
PRyMini.DeltaNeff = -1
PRyMDeltaNeff = PRyMmain.PRyMclass()

In [2]:
# [Neff , Ω_ν h^2 × 10^6 (rel), ∑ m_ν / (Ω_ν h^2) [eV], YP (CMB), YP (BBN), D/H × 10^5, 3He/H × 10^5, 7Li/H × 10^10]
PRyMDeltaNeff.PRyMresults()

array([ 2.0347102 ,  5.71377888, 92.85804906,  0.23098984,  0.23226129,
        2.1222465 ,  0.99173412,  5.95540689])

In [3]:
# Expectation: recover input DeltaNeff within numerical precision
(PRyMDeltaNeff.Neff()-PRyMSM.Neff())-PRyMini.DeltaNeff 

-0.009678321997505623

In [4]:
# Vary Lepton Asymmetry
PRyMini.DeltaNeff = 0.
PRyMini.munuOverTnu = 0.04 # implies roughly YP of 0.237, see 2206.00693
PRyMini.nacreii_flag = False
PRyMini.ReloadKeyRates()
PRyMXiNuPRIMAT = PRyMmain.PRyMclass()
PRyMini.nacreii_flag = True
PRyMini.ReloadKeyRates()
PRyMXiNuNACREII = PRyMmain.PRyMclass()

In [5]:
# Expectation: helium-4 mainly sensitive to weak rates
(PRyMXiNuNACREII.YPBBN()-PRyMXiNuPRIMAT.YPBBN())/0.237*100

-0.036567468502801966

In [6]:
# Scalar with mass mX = 0.1 MeV
PRyMini.munuOverTnu = 0.
import numpy as np
from scipy.integrate import quad
gX = 1; mX = 0.1;
def rho_NP(T_NP):
    if T_NP < mX/30.: return 0.
    else:
        res_int = quad(lambda E: E**2*(E**2-(mX/T_NP)**2)**0.5
        /(np.exp(E)-1.) ,mX/T_NP,100.,epsrel=1e-9,epsabs=1e-12)[0]
        return gX/(2*np.pi**2)*T_NP**4*res_int
def p_NP(T_NP):
    if T_NP < mX/30.: return 0.
    else:
        res_int = quad(lambda E: (E**2-(mX/T_NP)**2)**1.5
        /(np.exp(E)-1.) ,mX/T_NP,100.,epsabs=1e-9,epsrel=1e-12)[0]
        return gX/(6*np.pi**2)*T_NP**4*res_int
def drho_NP_dT(T_NP):
    if T_NP < mX/30.: return 0.
    else:
        res_int = quad(lambda E: 0.25*E**3*(E**2-(mX/T_NP)**2)**0.5*
        np.sinh(E/2.0)**-2 ,mX/T_NP,100,epsabs=1e-9,epsrel=1e-12)[0]
        return gX/(2*np.pi**2)*T_NP**3*res_int

In [7]:
# Adding e-philic species to thermal bath
PRyMini.aTid_flag = True
PRyMini.compute_bckg_flag = True
PRyMini.compute_nTOp_flag = True
PRyMini.NP_e_flag = True
PRyMephilic = PRyMmain.PRyMclass(rho_NP,p_NP,drho_NP_dT)
# [Neff , Ω_ν h^2 × 10^6 (rel), ∑ m_ν / (Ω_ν h^2) [eV], YP (CMB), YP (BBN), D/H × 10^5, 3He/H × 10^5, 7Li/H × 10^10]
PRyMephilic.PRyMresults()

array([  2.42947952,   4.54823454, 110.18690598,   0.26234923,
         0.2637341 ,   1.84848403,   0.94098227,   8.56948814])

In [8]:
# Adding e-philic species to thermal bath
PRyMini.aTid_flag = True
PRyMini.compute_bckg_flag = True
PRyMini.compute_nTOp_flag = True
PRyMini.NP_e_flag = False
PRyMini.NP_nu_flag = True
PRyMephilic = PRyMmain.PRyMclass(rho_NP,p_NP,drho_NP_dT)
# [Neff , Ω_ν h^2 × 10^6 (rel), ∑ m_ν / (Ω_ν h^2) [eV], YP (CMB), YP (BBN), D/H × 10^5, 3He/H × 10^5, 7Li/H × 10^10]
PRyMephilic.PRyMresults()

array([ 3.83701271,  7.18328085, 78.21138778,  0.25298604,  0.25433852,
        2.76314191,  1.0753871 ,  4.89881479])

In [13]:
# Vary Weak Rates wrt Born
PRyMini.NP_nTOp_flag = False
PRyMini.compute_nTOp_flag = True # need to recompute weak rates x Born approximation
PRyMini.nTOpBorn_flag = True
PRyMSMBorn = PRyMmain.PRyMclass()
PRyMini.compute_nTOp_flag = True # need to recompute weak rates due to NP
PRyMini.NP_nTOp_flag = True
PRyMini.NP_delta_nTOp = 0.1 # variation of neutron freeze out of O(10%) wrt Born prediction
PRyMNPnTOp = PRyMmain.PRyMclass()
(PRyMNPnTOp.YPBBN()-PRyMSMBorn.YPBBN())/PRyMSMBorn.YPBBN()*100

-7.004815159987158

In [14]:
# Vary Nuclear Rates wrt to Nominal Input
PRyMini.nTOpBorn_flag = False
PRyMini.compute_nTOp_flag = True
PRyMSM = PRyMmain.PRyMclass()
PRyMini.NP_nuclear_flag = True
PRyMini.compute_nTOp_flag = False # no need to recompute weak rates
PRyMini.NP_delta_npdg = 0.1 # variation of deuterium of O(10%) wrt nominal prediction
PRyMNPxDoH = PRyMmain.PRyMclass()
(PRyMNPxDoH.YPBBN()-PRyMSM.YPBBN())/PRyMSM.YPBBN()*100

7.167486838534172